<a href="https://colab.research.google.com/github/AnnabelleMcSharry/AI-ML-Car-Data/blob/main/Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install apyori
from apyori import apriori
import pandas as pd

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=35cc37dd8814c537f32bb9fdc63eec0aee4d1baed6155fdae900e58c4ebe4d0c
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [7]:
Invoices = pd.read_excel('Online Retail.xlsx')
print('Dimensions of dataset are :', Invoices.shape)
print(Invoices.head())

Dimensions of dataset are : (541909, 8)
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

In [8]:
pd.set_option('display.max_rows', None)
print(Invoices["Description"].value_counts())

Description
WHITE HANGING HEART T-LIGHT HOLDER     2369
REGENCY CAKESTAND 3 TIER               2200
JUMBO BAG RED RETROSPOT                2159
PARTY BUNTING                          1727
LUNCH BAG RED RETROSPOT                1638
ASSORTED COLOUR BIRD ORNAMENT          1501
SET OF 3 CAKE TINS PANTRY DESIGN       1473
PACK OF 72 RETROSPOT CAKE CASES        1385
LUNCH BAG  BLACK SKULL.                1350
NATURAL SLATE HEART CHALKBOARD         1280
POSTAGE                                1252
JUMBO BAG PINK POLKADOT                1251
HEART OF WICKER SMALL                  1237
JAM MAKING SET WITH JARS               1229
JUMBO STORAGE BAG SUKI                 1214
PAPER CHAIN KIT 50'S CHRISTMAS         1210
JUMBO SHOPPER VINTAGE RED PAISLEY      1202
LUNCH BAG CARS BLUE                    1197
LUNCH BAG SPACEBOY DESIGN              1192
JAM MAKING SET PRINTED                 1182
RECIPE BOX PANTRY YELLOW DESIGN        1180
SPOTTY BUNTING                         1172
LUNCH BAG SUKI DESIGN                  1139
ROSES REGENCY TEACUP AND SAUCER        1138
LUNCH BAG PINK POLKADOT                1137
WOODEN PICTURE FRAME WHITE FINISH      1129
SET OF 4 PANTRY JELLY MOULDS           1111
ALARM CLOCK BAKELIKE RED               1107
GREEN REGENCY TEACUP AND SAUCER        1085
LUNCH BAG APPLE DESIGN                 1084
VICTORIAN GLASS HANGING T-LIGHT        1072
RED RETROSPOT CHARLOTTE BAG            1068
LUNCH BAG WOODLAND                     1061
RABBIT NIGHT LIGHT                     1051
ALARM CLOCK BAKELIKE GREEN             1024
SET/20 RED RETROSPOT PAPER NAPKINS     1015
JUMBO BAG APPLES                       1009
WOODEN FRAME ANTIQUE WHITE              999
RETROSPOT TEA SET CERAMIC 11 PC         988
6 RIBBONS RUSTIC CHARM                  986
BAKING SET 9 PIECE RETROSPOT            974
REX CASH+CARRY JUMBO SHOPPER            967
HEART OF WICKER LARGE                   961
JUMBO  BAG BAROQUE BLACK WHITE          960
VINTAGE SNAP CARDS                      944
GARDENERS KNEELING PAD KEEP CALM        937
SET/5 RED RETROSPOT LID GLASS BOWLS     936
JUMBO BAG ALPHABET                      930
SPACEBOY LUNCH BOX                      924
SET OF 3 REGENCY CAKE TINS              919
CHARLOTTE BAG SUKI DESIGN               911
PACK OF 60 PINK PAISLEY CAKE CASES      896
JUMBO BAG VINTAGE LEAF                  895
CHOCOLATE HOT WATER BOTTLE              889
JUMBO BAG PINK VINTAGE PAISLEY          885
DOLLY GIRL LUNCH BOX                    881
JUMBO BAG WOODLAND ANIMALS              878
PLEASE ONE PERSON METAL SIGN            875
RED TOADSTOOL LED NIGHT LIGHT           874
60 TEATIME FAIRY CAKE CASES             871
SET OF 6 SPICE TINS PANTRY DESIGN       870
POPCORN HOLDER                          865
WOODLAND CHARLOTTE BAG                  858
JUMBO BAG STRAWBERRY                    850
PAPER CHAIN KIT VINTAGE CHRISTMAS       850
PINK REGENCY TEACUP AND SAUCER          829
HOT WATER BOTTLE KEEP CALM              813
PAPER BUNTING RETROSPOT                 812
ALARM CLOCK BAKELIKE PINK               810
HOME BUILDING BLOCK WORD                806
SCOTTIE DOG HOT WATER BOTTLE            798
CLOTHES PEGS RETROSPOT PACK 24          792
LUNCH BAG ALPHABET DESIGN               780
GARDENERS KNEELING PAD CUP OF TEA       780
CHARLOTTE BAG PINK POLKADOT             777
GIN + TONIC DIET METAL SIGN             775
RED HANGING HEART T-LIGHT HOLDER        773
STRAWBERRY CERAMIC TRINKET BOX          770
HANGING HEART JAR T-LIGHT HOLDER        767
ROUND SNACK BOXES SET OF4 WOODLAND      764
RECYCLING BAG RETROSPOT                 760
LUNCH BOX I LOVE LONDON                 750
COOK WITH WINE METAL SIGN               745
DOORMAT KEEP CALM AND COME IN           742
STRAWBERRY CHARLOTTE BAG                742
IVORY KITCHEN SCALES                    741
JUMBO BAG 50'S CHRISTMAS                739
JUMBO BAG VINTAGE DOILY                 737
PLASTERS IN TIN WOODLAND ANIMALS        729
GUMBALL COAT RACK                       728
JUMBO STORAGE BAG SKULLS                720
ANTIQUE SILVER T-LIGHT GLASS            719
DOTCOM POSTAGE                          709
PACK OF 20 NAPKINS PANTRY DESIGN        709
SET OF 3 BUTTERFLY COOKIE CUTTERS       707
DOORMAT RED RETROSPOT                   707
LUNCH BAG DOLLY GIRL DESIGN             706
JUMBO BAG SPACEBOY DESIGN               702
SET OF 3 HEART COOKIE CUTTERS           700
WOOD BLACK BOARD ANT WHITE FINISH       698
PLASTERS IN TIN SPACEBOY                697
LUNCH BAG VINTAGE LEAF DESIGN           692
GINGERBREAD MAN COOKIE CUTTER           691
HAND WARMER OWL DESIGN                  687
HAND OVER THE CHOCOLATE   SIGN          686
CHILLI LIGHTS                           679
HOT WATER BOTTLE I AM SO POORLY         679
PACK OF 72 SKULL CAKE CASES             678
RED  HARMONICA IN BOX                   676
JUMBO BAG SCANDINAVIAN BLUE PAISLEY     675
JUMBO BAG OWLS                          673
SET OF 60 PANTRY DESIGN CAKE CASES      659
SMALL WHITE HEART OF WICKER             657
HOT WATER BOTTLE TEA AND SYMPATHY       656
LOVE BUILDING BLOCK WORD                656
HOMEMADE JAM SCENTED CANDLES            655
RETROSPOT HEART HOT WATER BOTTLE        655
60 CAKE CASES VINTAGE CHRISTMAS         652
72 SWEETHEART FAIRY CAKE CASES          650
HOT BATHS METAL SIGN                    643
BATHROOM METAL SIGN                     641
PACK OF 60 DINOSAUR CAKE CASES          641
SET OF 20 VINTAGE CHRISTMAS NAPKINS     640
COLOUR GLASS T-LIGHT HOLDER HANGING     640
PINK CREAM FELT CRAFT TRINKET BOX       633
DOORMAT UNION FLAG                      627
TRADITIONAL KNITTING NANCY              625
LUNCH BAG VINTAGE DOILY                 624
PAPER CHAIN KIT RETROSPOT               619
VINTAGE HEADS AND TAILS CARD GAME       617
BLUE HARMONICA IN BOX                   615
HANGING HEART ZINC T-LIGHT HOLDER       612
SMALL POPCORN HOLDER                    611
ROUND SNACK BOXES SET OF 4 FRUITS       611
DOORMAT NEW ENGLAND                     608
JUMBO BAG PEARS                         608
WOODEN BOX OF DOMINOES                  607
BOX OF 24 COCKTAIL PARASOLS             603
WOOD 2 DRAWER CABINET WHITE FINISH      600
DOORMAT HEARTS                          599
STRAWBERRY LUNCH BOX WITH CUTLERY       598
GREY HEART HOT WATER BOTTLE             595
CHARLOTTE BAG APPLES DESIGN             594
ALARM CLOCK BAKELIKE IVORY              594
LARGE WHITE HEART OF WICKER             593
PLASTERS IN TIN SKULLS                  593
PLASTERS IN TIN CIRCUS PARADE           591
PLASTERS IN TIN VINTAGE PAISLEY         589
RED RETROSPOT SHOPPER BAG               586
HAND WARMER SCOTTY DOG DESIGN           585
SMALL GLASS HEART TRINKET POT           585
RED RETROSPOT CAKE STAND                584
RED KITCHEN SCALES                      577
HAND WARMER BIRD DESIGN                 574
CHILDRENS APRON SPACEBOY DESIGN         573
Manual                                  572
FELTCRAFT 6 FLOWER FRIENDS              568
SET OF 12 FAIRY CAKE BAKING CASES       567
CHRISTMAS CRAFT LITTLE FRIENDS          563
LOVEBIRD HANGING DECORATION WHITE       560
TRAVEL CARD WALLET KEEP CALM            557
WOODEN HEART CHRISTMAS SCANDINAVIAN     557
CREAM SWEETHEART MINI CHEST             555
ZINC METAL HEART DECORATION             552
EDWARDIAN PARASOL NATURAL               551
POTTERING IN THE SHED METAL SIGN        547
SMALL DOLLY MIX DESIGN ORANGE BOWL      546
RED RETROSPOT PICNIC BAG                546
SWEETHEART CERAMIC TRINKET BOX          543
WORLD WAR 2 GLIDERS ASSTD DESIGNS       542
PINK BLUE FELT CRAFT TRINKET BOX        538
CREAM HEART CARD HOLDER                 536
WOODEN STAR CHRISTMAS SCANDINAVIAN      535
PACK OF 60 SPACEBOY CAKE CASES          535
PLASTERS IN TIN STRONGMAN               534
PHOTO FRAME CORNICE                     533
SET OF 20 KIDS COOKIE CUTTERS           533
SET/6 RED SPOTTY PAPER PLATES           532
SUKI  SHOULDER BAG                      532
JUMBO BAG TOYS                          532
SPACEBOY BIRTHDAY CARD                  531
PACK OF 12 LONDON TISSUES               531
ENAMEL FLOWER JUG CREAM                 528
ASSORTED COLOURS SILK FAN               523
JUMBO BAG DOILEY PATTERNS               522
WHITE SKULL HOT WATER BOTTLE            518
HAND WARMER UNION JACK                  515
SET OF 72 PINK HEART PAPER DOILIES      514
FAWN BLUE HOT WATER BOTTLE              513
NATURAL SLATE CHALKBOARD LARGE          511
SINGLE HEART ZINC T-LIGHT HOLDER        510
SET OF TEA COFFEE SUGAR TINS PANTRY     509
DOORMAT FANCY FONT HOME SWEET HOME      506
FELTCRAFT BUTTERFLY HEARTS              506
RED RETROSPOT PEG BAG                   506
METAL 4 HOOK HANGER FRENCH CHATEAU      506
NO SINGING METAL SIGN                   505
LUNCH BAG DOILEY PATTERN                505
PANTRY MAGNETIC  SHOPPING LIST          503
LOVE HOT WATER BOTTLE                   502
PINK FAIRY CAKE CHILDRENS APRON         501
RECIPE BOX RETROSPOT                    499
4 TRADITIONAL SPINNING TOPS             498
LUNCH BOX WITH CUTLERY RETROSPOT        498
JUMBO BAG VINTAGE CHRISTMAS             496
SET/3 RED GINGHAM ROSE STORAGE BOX      494
SET OF 3 WOODEN HEART DECORATIONS       492
VINTAGE UNION JACK BUNTING              491
DOORMAT SPOTTY HOME SWEET HOME          489
SMALL HEART MEASURING SPOONS            489
FELTCRAFT CUSHION OWL                   488
LADIES & GENTLEMEN METAL SIGN           485
3 STRIPEY MICE FELTCRAFT                483
BAKING SET SPACEBOY DESIGN              483
TOY TIDY PINK POLKADOT                  482
PARTY METAL SIGN                        482
TEA TIME PARTY BUNTING                  478
CHOCOLATE THIS WAY METAL SIGN           478
TRAVEL SEWING KIT                       478
PICNIC BASKET WICKER SMALL              477
ZINC FOLKART SLEIGH BELLS               476
ROTATING SILVER ANGELS T-LIGHT HLDR     475
KNITTED UNION FLAG HOT WATER BOTTLE     473
ENAMEL BREAD BIN CREAM                  473
ALARM CLOCK BAKELIKE ORANGE             473
CHRISTMAS CRAFT TREE TOP ANGEL          473
RED DINER WALL CLOCK                    472
YOU'RE CONFUSING ME METAL SIGN          469
FELTCRAFT PRINCESS CHARLOTTE DOLL       469
PICNIC BASKET WICKER LARGE              466
SCANDINAVIAN REDS RIBBONS               465
SMALL MARSHMALLOWS PINK BOWL            464
MEMO BOARD RETROSPOT  DESIGN            464
RED RETROSPOT OVEN GLOVE                463
SET OF 72 RETROSPOT PAPER  DOILIES      462
SET OF 12 MINI LOAF BAKING CASES        460
RED RETROSPOT BOWL                      459
CHARLOTTE BAG VINTAGE ALPHABET          458
60 CAKE CASES DOLLY GIRL DESIGN         458
CLEAR DRAWER KNOB ACRYLIC EDWARDIAN     458
RED STRIPE CERAMIC DRAWER KNOB          458
BEWARE OF THE CAT METAL SIGN            458
REGENCY TEA PLATE ROSES                 458
SCANDINAVIAN PAISLEY PICNIC BAG         457
SET OF 6 SOLDIER SKITTLES               455
JUMBO BAG DOLLY GIRL DESIGN             454
ALARM CLOCK BAKELIKE CHOCOLATE          453
VINTAGE PAISLEY STATIONERY SET          453
TOILET SIGN OCCUPIED OR VACANT          452
DOORMAT WELCOME TO OUR HOME             452
POPPY'S PLAYHOUSE KITCHEN               451
TRADITIONAL WOODEN SKIPPING ROPE        451
BLUE STRIPE CERAMIC DRAWER KNOB         451
PACK OF 12 TRADITIONAL CRAYONS          450
WOODEN SCHOOL COLOURING SET             449
RED WOOLLY HOTTIE WHITE HEART.          449
SET 3 RETROSPOT TEA,COFFEE,SUGAR        449
PAPER CHAIN KIT EMPIRE                  448
WHITE WOOD GARDEN PLANT LADDER          447
CARD BILLBOARD FONT                     447
AREA PATROLLED METAL SIGN               445
IVORY DINER WALL CLOCK                  441
SET OF 3 NOTEBOOKS IN PARCEL            441
SET OF 6 RIBBONS VINTAGE CHRISTMAS      440
SOLDIERS EGG CUP                        439
SET/6 RED SPOTTY PAPER CUPS             439
REGENCY TEAPOT ROSES                    438
POPPY'S PLAYHOUSE BEDROOM               436
SET OF 60 I LOVE LONDON CAKE CASES      435
PACK OF 12 HEARTS DESIGN TISSUES        434
FLORAL FOLK STATIONERY SET              433
VINTAGE DOILY TRAVEL SEWING KIT         433
CHILDRENS CUTLERY POLKADOT PINK         431
RIBBON REEL STRIPES DESIGN              429
VINTAGE CREAM DOG FOOD CONTAINER        429
FELTCRAFT PRINCESS LOLA DOLL            428
SKULL LUNCH BOX WITH CUTLERY            427
NATURAL SLATE RECTANGLE CHALKBOARD      427
WHITE SPOT RED CERAMIC DRAWER KNOB      426
HAND WARMER RED LOVE HEART              425
BOX OF 6 MINI 50'S CRACKERS             425
CHARLOTTE BAG DOLLY GIRL DESIGN         425
PINK VINTAGE PAISLEY PICNIC BAG         425
TRADITIONAL WOODEN CATCH CUP GAME       424
WOOD S/3 CABINET ANT WHITE FINISH       424
GINGHAM HEART DECORATION                422
CHICK GREY HOT WATER BOTTLE             422
TRAVEL CARD WALLET VINTAGE TICKET       422
METAL SIGN TAKE IT OR LEAVE IT          422
PACK OF 6 BIRDY GIFT TAGS               420
STRAWBERRY SHOPPER BAG                  420
WICKER STAR                             419
FOUR HOOK  WHITE LOVEBIRDS              418
SET 6 SCHOOL MILK BOTTLES IN CRATE      418
CANDLEHOLDER PINK HANGING HEART         416
DOORMAT ENGLISH ROSE                    416
VINTAGE CHRISTMAS BUNTING               415
AIRLINE BAG VINTAGE TOKYO 78            413
SKULL SHOULDER BAG                      413
WOODEN UNION JACK BUNTING               412
CIRCUS PARADE LUNCH BOX                 411
TOILET METAL SIGN                       411
PINK HAPPY BIRTHDAY BUNTING             410
RED SPOTTY BISCUIT TIN                  409
PACK OF 60 MUSHROOM CAKE CASES          408
SWEETHEART CAKESTAND 3 TIER             407
CERAMIC STRAWBERRY CAKE MONEY BANK      406
BREAD BIN DINER STYLE IVORY             406
3 HOOK PHOTO SHELF ANTIQUE WHITE        403
SET/2 RED RETROSPOT TEA TOWELS          403
ENAMEL MEASURING JUG CREAM              403
VINTAGE SNAKES & LADDERS                401
RED RETROSPOT CUP                       400
FELTCRAFT CUSHION RABBIT                398
PANTRY WASHING UP BRUSH                 395
HAND WARMER RED RETROSPOT               395
SET OF 60 VINTAGE LEAF CAKE CASES       394
ASSORTED COLOUR MINI CASES              394
BLUE HAPPY BIRTHDAY BUNTING             394
SET OF 10 LED DOLLY LIGHTS              393
OPEN CLOSED METAL SIGN                  392
SET/10 RED POLKADOT PARTY CANDLES       392
BOX OF 6 MINI VINTAGE CRACKERS          391
CHRISTMAS CRAFT WHITE FAIRY             391
3 PIECE SPACEBOY COOKIE CUTTER SET      391
RED RETROSPOT MINI CASES                391
TRADITIONAL MODELLING CLAY              391
FAMILY ALBUM WHITE PICTURE FRAME        390
ENGLISH ROSE HOT WATER BOTTLE           390
MINI PAINT SET VINTAGE                  390
SET 7 BABUSHKA NESTING BOXES            389
HEART IVORY TRELLIS SMALL               389
SET OF 6 TEA TIME BAKING CASES          389
BLUE SPOT CERAMIC DRAWER KNOB           389
PACK OF 20 NAPKINS RED APPLES           389
REGENCY TEA PLATE GREEN                 388
EDWARDIAN PARASOL BLACK                 388
RED SPOT CERAMIC DRAWER KNOB            388
BINGO SET                               387
HAND WARMER BABUSHKA DESIGN             386
WHITE SPOT BLUE CERAMIC DRAWER KNOB     384
BLACK RECORD COVER FRAME                384
SET 2 PANTRY DESIGN TEA TOWELS          383
PAINTED METAL PEARS ASSORTED            382
LARGE HEART MEASURING SPOONS            382
KEY FOB , SHED                          380
MINT KITCHEN SCALES                     379
TREASURE TIN GYMKHANA DESIGN            379
COLOURING PENCILS BROWN TUBE            379
RED RETROSPOT UMBRELLA                  378
JINGLE BELL HEART DECORATION            377
SET 12 KIDS COLOUR  CHALK STICKS        376
MODERN FLORAL STATIONERY SET            376
SWEETHEART RECIPE BOOK STAND            375
CHILDRENS CUTLERY SPACEBOY              374
SAVE THE PLANET MUG                     374
12 PENCILS SMALL TUBE RED RETROSPOT     374
SET OF 4 KNICK KNACK TINS DOILY         373
BLUE DINER WALL CLOCK                   372
PACK OF 12 SUKI TISSUES                 372
I'M ON HOLIDAY METAL SIGN               372
MULTI COLOUR SILVER T-LIGHT HOLDER      372
12 PENCIL SMALL TUBE WOODLAND           372
CHILDRENS APRON APPLES DESIGN           372
RECIPE BOX BLUE SKETCHBOOK DESIGN       371
ANTIQUE SILVER TEA GLASS ENGRAVED       371
HANGING METAL HEART LANTERN             371
DOORMAT FAIRY CAKE                      371
WASHROOM METAL SIGN                     371
HOME SWEET HOME MUG                     370
12 PENCILS SMALL TUBE SKULL             370
RED RETROSPOT SMALL MILK JUG            369
TEA PARTY BIRTHDAY CARD                 369
RETROSPOT CHILDRENS APRON               369
RECORD FRAME 7" SINGLE SIZE             369
SET OF 6 SNACK LOAF BAKING CASES        369
TRADITIONAL CHRISTMAS RIBBONS           368
SET 12 RETRO WHITE CHALK STICKS         367
REVOLVER WOODEN RULER                   367
WOODEN ROUNDERS GARDEN SET              366
SET OF 36 PAISLEY FLOWER DOILIES        366
JAM JAR WITH PINK LID                   366
TEA BAG PLATE RED RETROSPOT             364
ROLL WRAP 50'S CHRISTMAS                364
HEART DECORATION RUSTIC HANGING         363
PICTURE DOMINOES                        363
SET 20 NAPKINS FAIRY CAKES DESIGN       363
CERAMIC HEART FAIRY CAKE MONEY BANK     363
T-LIGHT GLASS FLUTED ANTIQUE            361
RETROSPOT LARGE MILK JUG                361
HANGING JAM JAR T-LIGHT HOLDER          359
ROBOT BIRTHDAY CARD                     359
BUNDLE OF 3 ALPHABET EXERCISE BOOKS     359
FELTCRAFT CUSHION BUTTERFLY             358
SET/10 PINK POLKADOT PARTY CANDLES      358
PIGGY BANK RETROSPOT                    357
LAUNDRY 15C METAL SIGN                  356
AGED GLASS SILVER T-LIGHT HOLDER        355
JUMBO BAG PAISLEY PARK                  355
BALLOONS  WRITING SET                   353
RED RETROSPOT ROUND CAKE TINS           352
WOODEN TREE CHRISTMAS SCANDINAVIAN      351
VINTAGE CHRISTMAS STOCKING              351
PINK BABY BUNTING                       351
ENGLISH ROSE NOTEBOOK A7 SIZE           350
ROLL WRAP VINTAGE CHRISTMAS             350
CLASSIC CAFE SUGAR DISPENSER            349
DOUGHNUT LIP GLOSS                      348
PLAYING CARDS KEEP CALM & CARRY ON      347
GIANT 50'S CHRISTMAS CRACKER            346
36 PENCILS TUBE RED RETROSPOT           345
PLACE SETTING WHITE HEART               345
POTTERING MUG                           345
DELUXE SEWING KIT                       345
SET OF 3 HANGING OWLS OLLIE BEAK        345
FRENCH ENAMEL CANDLEHOLDER              344
FELTCRAFT DOLL MOLLY                    344
SET OF 3 WOODEN STOCKING DECORATION     343
REGENCY MILK JUG PINK                   343
WATERING CAN BLUE ELEPHANT              343
REGENCY SUGAR BOWL GREEN                342
PAPER BUNTING WHITE LACE                342
PACK OF 20 SKULL PAPER NAPKINS          342
PINK POLKADOT BOWL                      340
RED RETROSPOT WRAP                      339
FELTCRAFT CHRISTMAS FAIRY               339
LUNCH BAG PAISLEY PARK                  339
SET OF 36 TEATIME PAPER DOILIES         339
CLASSIC GLASS COOKIE JAR                338
6 GIFT TAGS VINTAGE CHRISTMAS           337
LANTERN CREAM GAZEBO                    336
6 GIFT TAGS 50'S CHRISTMAS              335
POPPY'S PLAYHOUSE LIVINGROOM            335
RETROSPOT PARTY BAG + STICKER SET       334
BLUE POLKADOT CUP                       334
RIBBON REEL HEARTS DESIGN               334
HEART IVORY TRELLIS LARGE               333
CHRISTMAS LIGHTS 10 REINDEER            333
IVORY HANGING DECORATION  HEART         331
PHOTO CUBE                              331
EDWARDIAN PARASOL RED                   330
SILVER HANGING T-LIGHT HOLDER           329
LONDON BUS COFFEE MUG                   328
CHOCOLATE BOX RIBBONS                   328
WHITE METAL LANTERN                     328
VINTAGE CREAM CAT FOOD CONTAINER        327
FANCY FONT BIRTHDAY CARD,               327
RIBBON REEL CHRISTMAS SOCK BAUBLE       327
10 COLOUR SPACEBOY PEN                  327
BLUE POLKADOT BOWL                      327
CHILDRENS CUTLERY RETROSPOT RED         324
3 HEARTS HANGING DECORATION RUSTIC      323
ROTATING LEAVES T-LIGHT HOLDER          322
TEA TIME OVEN GLOVE                     322

In [10]:
description_counts = Invoices['Description'].value_counts()
descriptions_to_keep = description_counts[description_counts >= 10].index
Invoices = Invoices[Invoices['Description'].isin(descriptions_to_keep)]
print('Shape of Invoices after filtering:', Invoices.shape)
print('First 5 rows of filtered Invoices:\n', Invoices.head())

Shape of Invoices after filtering: (537019, 8)
First 5 rows of filtered Invoices:
   InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

In [9]:
duplicates = Invoices.duplicated()
print(f"Number of duplicate rows: {duplicates.sum()}")

# Check for missing data
missing_data = Invoices.isnull().sum()
print("\nMissing data in each column:")
print(missing_data)

Number of duplicate rows: 5268

Missing data in each column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [11]:
Invoices.drop_duplicates(inplace=True)
print(f"Shape after dropping duplicates: {Invoices.shape}")

# Dropping rows where 'Description' or 'CustomerID' is NaN
Invoices.dropna(subset=['Description', 'CustomerID'], inplace=True)
print(f"Shape after dropping missing values: {Invoices.shape}")

Shape after dropping duplicates: (531768, 8)
Shape after dropping missing values: (399361, 8)

### Task 4 - Grouping the data for Market Basket Analysis

First, we'll ensure the `InvoiceDate` column is in datetime format and then extract the `YearMonth` to facilitate monthly grouping. We'll then create three different groupings:

1.  **`InvoiceMonth_group`**: Lists all item descriptions purchased within each month.
2.  **`Customer_group`**: Lists all item descriptions purchased by each unique customer.
3.  **`Customer_Month_Group`**: Lists all item descriptions purchased by each unique customer within each month.

In [13]:
import pandas as pd

# The 'InvoiceDate' column is already in datetime format from pd.read_excel.
# No need for: Invoices['InvoiceDate'] = pd.to_datetime(Invoices['InvoiceDate'])

# Extract Year-Month and create a new column
Invoices['YearMonth'] = Invoices['InvoiceDate'].dt.to_period('M')

# Grouping 1: Items purchased per month
InvoiceMonth_group = Invoices.groupby('YearMonth')['Description'].apply(list).reset_index()

# Grouping 2: Items purchased by each customer
Customer_group = Invoices.groupby('CustomerID')['Description'].apply(list).reset_index()

# Grouping 3: Items purchased by each customer per month
Customer_Month_Group = Invoices.groupby(['CustomerID','YearMonth'])['Description'].apply(list).reset_index()


print('InvoiceMonth_group head (items purchased per month):')
display(InvoiceMonth_group.head())
print('\nCustomer_group head (all items purchased by each customer):')
display(Customer_group.head())
print('\nCustomer_Month_Group head (items purchased by each customer per month):')
display(Customer_Month_Group.head())

InvoiceMonth_group head (items purchased per month):

  YearMonth                                        Description
0   2010-12  [WHITE HANGING HEART T-LIGHT HOLDER, WHITE MET...
1   2011-01  [JUMBO BAG PINK POLKADOT, BLUE POLKADOT WRAP, ...
2   2011-02  [RED SPOT CERAMIC DRAWER KNOB, RED STRIPE CERA...
3   2011-03  [DOORMAT UNION JACK GUNS AND ROSES, DOORMAT HE...
4   2011-04  [LUNCH BAG DOLLY GIRL DESIGN, HEART IVORY TREL...

Customer_group head (all items purchased by each customer):

   CustomerID                                        Description
0     12346.0  [MEDIUM CERAMIC TOP STORAGE JAR, MEDIUM CERAMI...
1     12347.0  [BLACK CANDELABRA T-LIGHT HOLDER, AIRLINE BAG ...
2     12348.0  [72 SWEETHEART FAIRY CAKE CASES, 60 CAKE CASES...
3     12349.0  [PARISIENNE CURIO CABINET, SWEETHEART WALL TID...
4     12350.0  [CHOCOLATE THIS WAY METAL SIGN, METAL SIGN NEI...

Customer_Month_Group head (items purchased by each customer per month):

   CustomerID YearMonth                                        Description
0     12346.0   2011-01  [MEDIUM CERAMIC TOP STORAGE JAR, MEDIUM CERAMI...
1     12347.0   2010-12  [BLACK CANDELABRA T-LIGHT HOLDER, AIRLINE BAG ...
2     12347.0   2011-01  [PINK NEW BAROQUECANDLESTICK CANDLE, BLUE NEW ...
3     12347.0   2011-04  [AIRLINE BAG VINTAGE JET SET WHITE, AIRLINE BA...
4     12347.0   2011-06  [RABBIT NIGHT LIGHT, REGENCY TEA STRAINER, REG...